---
- hosts: benchservers
  sudo: yes
  gather_facts: no
  tasks:
    - name: change timezone to JST
      shell: cp -p /usr/share/zoneinfo/Japan /etc/localtime
    - group: name=wheel
    - user: name=vagrant groups=wheel
    - copy: src=../files/bashrc dest=/home/isucon/.bashrc owner=vagrant mode=755
    - lineinfile: dest=/etc/sudoers state=present regexp='^%wheel ALL\=' line='%wheel ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
    - shell: update-locale LANG=ja_JP.UTF-8
    - shell: chown -R vagrant:wheel /home/isucon
